
# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-O2 -pipe -march=native"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

EMERGE_DEFAULT_OPTS="--jobs=5 --load-average=$(nproc)"
MAKEOPTS="-j$(nproc)"


LINGUAS="ru en"

# Графика
VIDEO_CARDS="vboxvideo"
# VIDEO_CARDS="amdgpu radeonsi"   # AMD
# VIDEO_CARDS="intel i915 iris" # Intel
# VIDEO_CARDS="nvidia"          # NVIDIA (proprietary)

INPUT_DEVICES="libinput"

USE="
X
xorg
kde plasma qt6
opengl egl
dbus udev
networkmanager
pipewire
sddm
"

# Qt / KDE
QT_TARGET="qt6"
QT6_TARGET="qt6"

# Python (Plasma 6 уже почти не зависит, но пусть будет)
PYTHON_SINGLE_TARGET="python3_12"
PYTHON_TARGETS="python3_13 python3_12"

# License
ACCEPT_LICENSE="*"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8
