  GNU nano 8.7                             /etc/portage/binrepos.conf/gentoobinhost.conf
# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consider using a local mirror.

[gentoo]
priority = 1
# sync-uri = https://distfiles.gentoo.org/releases/amd64/binpackages/23.0/x86-64
sync-uri = https://mirror.yandex.ru/gentoo-distfiles/releases/amd64/binpackages/23.0/x86-64/
location = /var/cache/binhost/gentoo
verify-signature = true

[binhost]
priority = 9999
#sync-uri = https://distfiles.gentoo.org/releases/amd64/binpackages/23.0/x86-64/
sync-uri = https://mirror.yandex.ru/gentoo-distfiles/releases/amd64/binpackages/23.0/x86-64/
