# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

USE="systemd grub alsa dbus networkmanager pipewire pulseaudio dracut"
# USE="${USE} X wayland plasma qt5 qt6 kde ufw crypt flatpak"
# USE="bluetooth -efistub -grub -refind -systemd-boot -ugrd -uki -ukify wacom"
ACCEPT_KEYWORDS="~amd64"

VIDEO_CARDS="vmware" # Для VMWARE
INPUT_DEVICES="libinput" # для VMWARE

ABI_X86="64 32"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

MAKEOPTS="-j4 -l5"
EMERGE_DEFAULT_OPTS="--jobs=3 --load-average=5"

FEATURES="${FEATURES} getbinpkg"
# Require signatures
FEATURES="${FEATURES} binpkg-request-signature"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8
ACCEPT_LICENSE="-* @FREE @BINARY-REDISTRIBUTABLE"

GRUB_PLATFORMS="efi-64"

GENTOO_MIRRORS="https://gentoo-mirror.alexxy.name/ \
    http://gentoo-mirror.alexxy.name/ \
    https://ru.mirrors.cicku.me/gentoo/ \
    http://ru.mirrors.cicku.me/gentoo/ \
    https://mirror.yandex.ru/gentoo-distfiles/ \
    http://mirror.yandex.ru/gentoo-distfiles/ \
    ftp://mirror.yandex.ru/gentoo-distfiles/"