version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    hostname: jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - ./data:/var/jenkins_home
    networks:
      - jenkins
  agent1:
    image: jenkins/ssh-agent:alpine-jdk17
    container_name: agent1
    hostname: agent1
    ports:
      - '4444:22'
    volumes:
      - ./adata:/home/jenkins/data
    environment:
      JENKINS_AGENT_SSH_PUBKEY: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC86C17At3y7HrbNRW92SjfSPAsDObKkXC/OJfprC8dZ'
    networks:
      - jenkins

networks:
  jenkins:
    # Use a custom driver
    driver: bridge
