conky.config = {
    background=false,
    update_interval=2,
    double_buffer=true,
    no_buffers=true,
    imlib_cache_size=10,

    draw_shades=false,
    draw_outline=false,
    draw_borders=false,

    gap_x=150,
    gap_y=30,

    alignment="tr",

    minimum_height=400,
    minimum_width=0,

    own_window = true,
    own_window_type = "desktop",
    own_window_transparent = true,
    own_window_hints="undecorated,below,sticky,skip_taskbar,skip_pager",

    own_window_argb_visual=true,
    own_window_argb_value=0,

    use_xft=true,
    xftalpha=1,
    font = 'DejaVu Sans Mono:size=10',
    text_buffer_size=256,
    override_utf8_locale=true,

    default_color='FFFFFF',
    color0='FFFFFF',
}

conky.text = [[
${font DejaVu Sans Mono:weight=Bold:size=40}${color0}${time %A}\
${voffset 0}
${font DejaVu Sans Mono:weight=Bold:size=30}${color0}${time %d %B %Y}\
${voffset 0}
${font DejaVu Sans Mono:weight=Bold:size=90}${color0}${time %H:%M}\
${voffset -100}
${font DejaVu Sans Mono:weight=Bold:size=14}${color0}CPU: ${cpu}%
${font DejaVu Sans Mono:weight=Bold:size=14}${color0}Free: ${fs_free /} (${fs_free_perc /}%)
${font DejaVu Sans Mono:weight=Bold:size=14}${color0}MEM: ${memperc}% ${mem}/${memmax}\
${voffset -10}
${if_match "${execi 1 bash -c 'set +x; exec playerctl -p strawberry status 2>/dev/null'}" == "Playing"}
${font DejaVu Sans Mono:weight=Bold:size=20}${color0}
${execi 1 bash -c "set +x; playerctl -p strawberry metadata artist 2>/dev/null"}
${execi 1 bash -c "set +x; playerctl -p strawberry metadata title 2>/dev/null"}
${endif}
]]
